### ISSUE TITLE
Add callback or promise for authentication

### ISSUE THREAD

**Issue by leonzinger** [christiansmith/ngDropbox#2]
Hi Christian,

is it possible to add a callback when user authenticated? or i will just do a pull-request ;)

Thanks

**Comment by christiansmith** [comment]
Good catch. It's on the TODO list.

**Comment by christiansmith** [comment]
Dropbox.authenticate() now returns a promise. Let me know if this works out for you.

https://github.com/christiansmith/ngDropbox/commit/26343a97da9556cf32c27a9557f91cce859f0b81

**Comment by leonzinger** [comment]
Thanks a lot Christian. I will try it out as soon as possible

**Comment by thrashr888** [comment]
This works for me.

**Comment by leonzinger** [comment]
Great, tomorrow morning I'll try it out
