### ISSUE TITLE
Suggestion for authentication method (maybe)

### ISSUE THREAD

**Issue by aaroneiche** [christiansmith/ngDropbox#5]
Hi, 

I am very new to both AngularJS and the dropbox API, but I've been trying to build an application and I ran into an issue trying to use the promise that it returns. I _think_ I've fixed it, but I could be way off here.

The previous code for the listener on the authenticate method looks like this: 

```
function listener(event) {
              oauth = queryParamsFromUrl(event.data);
              self.oauth = oauth;
              deferred.resolve(oauth);
              console.log('Dropbox', self);
            }

$window.addEventListener('message', listener, false);
```

which works, but assumes that the first message coming back is going to be a successful login. In my experiments (which again, may be entirely wrong) I was getting back 3 messages before the message with the token. I haven't researched enough to figure out what these were (and if it makes a difference, I'm running my app as a 'Static Web App' from in dropbox instead on an external domain...)

The way I fixed it was to introduce this:

```
function listener(event) {
    oauth = queryParamsFromUrl(event.data);
    self.oauth = oauth;
    if(self.oauth.access_token != undefined){
        deferred.resolve(oauth);                
    }else{
        deferred.notify("-1");
    }
}
```

The notify message obviously needs to be something else. Is this a beneficial change? Is there a better way to test for a successful login?

**Comment by christiansmith** [comment]
Aaron, thanks for posting the issue. I'll make time to dive in this weekend. Glad to help out/pair program via Google Hangout if that would be helpful.

**Comment by thrashr888** [comment]
`-1` in promise parlance would instead be `deferred.reject("reason")`.

**Comment by aaroneiche** [comment]
I was under the impression that notify would be more appropriate than reject in this case, because we're still expecting a successful resolution. I agree though that there should be a reject as well.

I think my only obstacle to submitting a pull request to fix would be I don't have a test environment setup, and every time I go to do it it looks daunting ;)

**Comment by christiansmith** [comment]
@aaroneiche, you definitely uncovered a bug. The event listener needed to remove itself when called. This is why there were multiple messages coming back. Each successive time you called authenticate, the callback was being registered and invoked an additional time.  

I think @thrashr888's right about reject in this case. If there is an access_denied property in the dropbox redirect_uri fragment, the promise will be rejected with the access_denied error/description as the argument. 

Thanks guys for your input! Really appreciate the issues and comments. Please let me know if this works out for you so I can close the issue.

**Comment by christiansmith** [comment]
Forgot to mention I just pushed the fix: https://github.com/christiansmith/ngDropbox/commit/1e3721360eeba66a603544b14d62a53470b6bcd8
